// <auto-generated />
using System;
using BazarPapelaria10.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BazarPapelaria10.Migrations
{
    [DbContext(typeof(BazarPapelaria10Context))]
    [Migration("20200401234632_BancoInicial")]
    partial class BancoInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BazarPapelaria10.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Ativo");

                    b.Property<string>("Desccateg");

                    b.Property<DateTime>("Dtalteracao");

                    b.Property<DateTime>("Dtcriacao");

                    b.Property<string>("Nomecateg");

                    b.Property<string>("Obscateg");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("BazarPapelaria10.Models.Prodcateg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CategoriaCodCateg");

                    b.Property<DateTime>("Dtalteracao");

                    b.Property<DateTime>("Dtcriacao");

                    b.Property<int>("ProdutoCodProd");

                    b.HasKey("Id");

                    b.ToTable("Prodcategs");
                });

            modelBuilder.Entity("BazarPapelaria10.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Ativo");

                    b.Property<string>("Descprod");

                    b.Property<DateTime>("Dtalteracao");

                    b.Property<DateTime>("Dtcriacao");

                    b.Property<string>("Nomeprod");

                    b.Property<string>("Obsprod");

                    b.Property<string>("Valorprod");

                    b.HasKey("Id");

                    b.ToTable("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
